version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install bundler and update system rubygems.
          command: |
            echo 'export BUNDLER_VERSION=$( grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -v $BUNDLER_VERSION

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Download CodeClimate cc-test-reporter
          command: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

      - run:
          name: Make cc-test-reporter executable
          command: chmod +x ./cc-test-reporter

      - run:
          name: Report before build to CodeClimate
          command: ./cc-test-reporter before-build

      - run:
          name: run tests
          command: bundle exec rspec

      - run:
          name: Report after build to CodeClimate
          command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context:
            - docker-credential
